/**
 * Pre-generates the official maps into src/maps.generated.ts so all peers share identical tile data.
 * Run: pnpm --filter @rookfall/sim gen-maps
 */
import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { OFFICIAL_MAPS, RANDOM_MAP_ID, generateMap, serializeMap } from '../src/map';

const here = dirname(fileURLToPath(import.meta.url));
const out: string[] = ['/* AUTO-GENERATED by scripts/gen-maps.ts - do not edit. */', 'export const GENERATED_MAPS: Record<string, string> = {'];
for (const info of OFFICIAL_MAPS) {
  if (info.id === RANDOM_MAP_ID) continue; // rolled per match from the seed
  const m = generateMap(info.id);
  const s = serializeMap(m);
  out.push(`  ${JSON.stringify(info.id)}: ${JSON.stringify(s)},`);
  console.log(`${info.id}: ${m.w}x${m.h}, ${m.mines.length} mines, ${m.starts.length} starts, ${m.decor.length} decor, ${(s.length / 1024).toFixed(1)} KB`);
}
out.push('};', '');
writeFileSync(join(here, '../src/maps.generated.ts'), out.join('\n'));
console.log('written src/maps.generated.ts');
