// Generated by scripts/build-icons.mjs from src/ui/icons/svg/*.svg and src/ui/icons/aliases.json (paths in packages/client). Do not edit by hand.
// Inner SVG markup per icon; ids are written as __ID__<n> and made unique per rendered icon by Icon.tsx.

export interface IconDef { readonly viewBox: string; readonly body: string }

const i_abl_incendiary: IconDef = { viewBox: '0 0 24 24', body: '<defs><mask id="__ID__0" maskUnits="userSpaceOnUse" x="0" y="0" width="24" height="24"><rect width="24" height="24" fill="#fff"/><g fill="#000"><path d="M12 12.6c1.2 1.6 3.2 2.8 3.2 5a3.2 3.2 0 0 1-6.4 0c0-1.4.8-2.4 1.8-3 .2 1 .6 1.6 1.2 1.8-.4-1.4-.4-2.6.2-3.8z"/></g></mask></defs><g mask="url(#__ID__0)"><path d="M12.6 2C13.4 5.6 18.8 8.4 18.8 14.4a6.8 6.8 0 0 1-13.6 0C5.2 11.4 6.6 9.4 8.4 8c0 2 .8 3.4 2 4C10 8 11.2 4.6 12.6 2z"/></g>' };
const i_abl_shield: IconDef = { viewBox: '0 0 24 24', body: '<defs><mask id="__ID__0" maskUnits="userSpaceOnUse" x="0" y="0" width="24" height="24"><rect width="24" height="24" fill="#fff"/><g fill="#000"><path d="M7.6 3.4h8.8v7.39q0 7.04-4.4 10.21q-4.4-3.17-4.4-10.21z" stroke="#000" stroke-width="2.6" stroke-linejoin="round"/></g></mask></defs><g mask="url(#__ID__0)"><path d="M1.8 7h7.6v5.29q0 5.04-3.8 7.31q-3.8-2.27-3.8-7.31z"/><path d="M14.6 7h7.6v5.29q0 5.04-3.8 7.31q-3.8-2.27-3.8-7.31z"/></g><g><path d="M7.6 3.4h8.8v7.39q0 7.04-4.4 10.21q-4.4-3.17-4.4-10.21z"/></g>' };
const i_abl_volley: IconDef = { viewBox: '0 0 24 24', body: '<g><g transform="rotate(-30 12 12)"><rect x="4.6" y="2.4" width="2" height="10"/><path d="M2.8 12h5.6L5.6 17.4z"/><rect x="11" y="5" width="2" height="10"/><path d="M9.2 14.6h5.6L12 20z"/><rect x="17.4" y="2.4" width="2" height="10"/><path d="M15.6 12h5.6L18.4 17.4z"/></g></g>' };
const i_account: IconDef = { viewBox: '0 0 24 24', body: '<g><circle cx="12" cy="7.6" r="4.1"/><path d="M3.8 21.8v-4.14a8.2 5.7 0 0 1 16.4 0v4.14z"/></g>' };
const i_age_1: IconDef = { viewBox: '0 0 24 24', body: '<defs><mask id="__ID__0" maskUnits="userSpaceOnUse" x="0" y="0" width="24" height="24"><rect width="24" height="24" fill="#fff"/><g fill="#000"><rect x="11" y="7" width="2" height="7.8"/><rect x="9.2" y="6.4" width="5.6" height="1.6"/><rect x="9.2" y="14.2" width="5.6" height="1.6"/></g></mask></defs><g mask="url(#__ID__0)"><rect x="3.2" y="2" width="17.6" height="2" rx=".6"/><path d="M5.2 4h13.6v17L12 17.4 5.2 21z"/></g>' };
const i_age_2: IconDef = { viewBox: '0 0 24 24', body: '<defs><mask id="__ID__0" maskUnits="userSpaceOnUse" x="0" y="0" width="24" height="24"><rect width="24" height="24" fill="#fff"/><g fill="#000"><rect x="8.9" y="7" width="2" height="7.8"/><rect x="13.1" y="7" width="2" height="7.8"/><rect x="7.6" y="6.4" width="8.8" height="1.6"/><rect x="7.6" y="14.2" width="8.8" height="1.6"/></g></mask></defs><g mask="url(#__ID__0)"><rect x="3.2" y="2" width="17.6" height="2" rx=".6"/><path d="M5.2 4h13.6v17L12 17.4 5.2 21z"/></g>' };
const i_age_up: IconDef = { viewBox: '0 0 24 24', body: '<defs><mask id="__ID__0" maskUnits="userSpaceOnUse" x="0" y="0" width="24" height="24"><rect width="24" height="24" fill="#fff"/><g fill="#000"><path d="M12 6.4l4.6 4.8h-3.4v4.6h-2.4v-4.6H7.4z"/></g></mask></defs><g mask="url(#__ID__0)"><rect x="3.2" y="2" width="17.6" height="2" rx=".6"/><path d="M5.2 4h13.6v17L12 17.4 5.2 21z"/></g>' };
const i_armor: IconDef = { viewBox: '0 0 24 24', body: '<defs><mask id="__ID__0" maskUnits="userSpaceOnUse" x="0" y="0" width="24" height="24"><rect width="24" height="24" fill="#fff"/><g fill="#000"><rect x="5.8" y="9.6" width="12.4" height="1.8" rx=".3"/><rect x="11.1" y="9.6" width="1.8" height="7.4" rx=".3"/><path d="M12 2v5.4" fill="none" stroke="#000" stroke-width="1.2" stroke-linecap="butt" stroke-linejoin="round"/></g></mask></defs><g mask="url(#__ID__0)"><path d="M4.2 21.4V9.6C4.2 5.2 7.6 2.4 12 2.4s7.8 2.8 7.8 7.2v11.8z"/></g>' };
const i_attack_move: IconDef = { viewBox: '0 0 24 24', body: '<g><g transform="rotate(45 12 12)"><path d="M7 9.4 12 1.6l5 7.8-5-1.8z"/><rect x="10.8" y="7" width="2.4" height="8.4"/><rect x="7.4" y="15" width="9.2" height="2.2" rx=".6"/><rect x="11" y="16.6" width="2" height="3.4"/><circle cx="12" cy="21.2" r="1.6"/></g></g>' };
const i_back: IconDef = { viewBox: '0 0 24 24', body: '<g><path d="M2.6 12 10.4 4.4v4.5h11l-2.6 3.1 2.6 3.1h-11v4.5z"/></g>' };
const i_barracks: IconDef = { viewBox: '0 0 24 24', body: '<defs><mask id="__ID__0" maskUnits="userSpaceOnUse" x="0" y="0" width="24" height="24"><rect width="24" height="24" fill="#fff"/><g fill="#000"><rect x="10" y="15.4" width="4" height="4.6"/><rect x="4.8" y="15.2" width="2.8" height="2.2"/><rect x="16.4" y="15.2" width="2.8" height="2.2"/></g></mask></defs><g mask="url(#__ID__0)"><rect x="1.5" y="20" width="21" height="2" rx=".6"/><path d="M1.6 11.8 5 7.6h14l3.4 4.2z"/><rect x="2.6" y="13" width="18.8" height="8"/><rect x="11.2" y="1.4" width="1.6" height="6.6"/><path d="M12.8 1.8l6 1.7-6 1.7z"/></g>' };
const i_build: IconDef = { viewBox: '0 0 24 24', body: '<g><g transform="rotate(45 12 12)"><rect x="10.8" y="8.6" width="2.4" height="13.4" rx=".8"/><path d="M6 3.4h10.2l2.4 1.6v3.2H6z"/></g></g>' };
const i_cancel: IconDef = { viewBox: '0 0 24 24', body: '<defs><mask id="__ID__0" maskUnits="userSpaceOnUse" x="0" y="0" width="24" height="24"><rect width="24" height="24" fill="#fff"/><g fill="#000"><g transform="rotate(45 12 12)"><rect x="10.9" y="5.6" width="2.2" height="12.8" rx=".5"/></g><g transform="rotate(-45 12 12)"><rect x="10.9" y="5.6" width="2.2" height="12.8" rx=".5"/></g></g></mask></defs><g mask="url(#__ID__0)"><circle cx="12" cy="12" r="10"/></g>' };
const i_castle: IconDef = { viewBox: '0 0 24 24', body: '<defs><mask id="__ID__0" maskUnits="userSpaceOnUse" x="0" y="0" width="24" height="24"><rect width="24" height="24" fill="#fff"/><g fill="#000"><path d="M10.2 20v-3.6a1.8 1.8 0 0 1 3.6 0V20z"/><rect x="4.75" y="10.2" width="1.5" height="3.2"/><rect x="17.75" y="10.2" width="1.5" height="3.2"/></g></mask></defs><g mask="url(#__ID__0)"><rect x="1.5" y="20" width="21" height="2" rx=".6"/><rect x="2.8" y="7" width="5.4" height="14"/><rect x="2.8" y="4.6" width="1.7" height="3"/><rect x="6.5" y="4.6" width="1.7" height="3"/><rect x="15.8" y="7" width="5.4" height="14"/><rect x="15.8" y="4.6" width="1.7" height="3"/><rect x="19.5" y="4.6" width="1.7" height="3"/><rect x="8" y="10.4" width="8" height="10.6"/><rect x="8" y="8.4" width="1.6" height="2.4"/><rect x="11.2" y="8.4" width="1.6" height="2.4"/><rect x="14.4" y="8.4" width="1.6" height="2.4"/></g>' };
const i_chart: IconDef = { viewBox: '0 0 24 24', body: '<g><rect x="2.6" y="2.6" width="2.2" height="18.8" rx=".5"/><rect x="2.6" y="19.2" width="18.8" height="2.2" rx=".5"/><path d="M6.8 17.4v-3.8l3.8-5 3.3 3 4.4-6.4 2.7 2.2v10z"/></g>' };
const i_chat: IconDef = { viewBox: '0 0 24 24', body: '<defs><mask id="__ID__0" maskUnits="userSpaceOnUse" x="0" y="0" width="24" height="24"><rect width="24" height="24" fill="#fff"/><g fill="#000"><rect x="6.2" y="7.2" width="11.6" height="1.6" rx=".5"/><rect x="6.2" y="11" width="7.6" height="1.6" rx=".5"/></g></mask></defs><g mask="url(#__ID__0)"><path d="M2.8 5.6A2.6 2.6 0 0 1 5.4 3h13.2a2.6 2.6 0 0 1 2.6 2.6v8.6a2.6 2.6 0 0 1-2.6 2.6h-7.4L6 21v-4.2h-.6a2.6 2.6 0 0 1-2.6-2.6z"/></g>' };
const i_check: IconDef = { viewBox: '0 0 24 24', body: '<g><path d="M2.8 12.6 5.1 10.3l4.6 4.6 9.2-9.2 2.3 2.3L9.7 19.5z"/></g>' };
const i_chevron: IconDef = { viewBox: '0 0 24 24', body: '<g><path d="M5 8.4 12 15.4l7-7 1.8 1.8-8.8 8.8-8.8-8.8z"/></g>' };
const i_clear: IconDef = { viewBox: '0 0 24 24', body: '<defs><mask id="__ID__0" maskUnits="userSpaceOnUse" x="0" y="0" width="24" height="24"><rect width="24" height="24" fill="#fff"/><g fill="#000"><path d="M10.3 15.6 9.2 23M13.7 15.6l1.1 7.4" fill="none" stroke="#000" stroke-width="1.2" stroke-linecap="butt" stroke-linejoin="round"/></g></mask></defs><g transform="translate(12 12) scale(.95) translate(-12 -12) translate(2.59 -2.27) rotate(40 12 12)"><g mask="url(#__ID__0)"><rect x="10.7" y="2.4" width="2.6" height="8.4" rx="1"/><rect x="8.2" y="10.2" width="7.6" height="3" rx=".6"/><path d="M7.8 14.4h8.4l3.2 8H4.6z"/></g></g>' };
const i_close: IconDef = { viewBox: '0 0 24 24', body: '<g><g transform="rotate(45 12 12)"><rect x="10.9" y="2.6" width="2.2" height="18.8" rx=".6"/></g><g transform="rotate(-45 12 12)"><rect x="10.9" y="2.6" width="2.2" height="18.8" rx=".6"/></g></g>' };
const i_copy: IconDef = { viewBox: '0 0 24 24', body: '<defs><mask id="__ID__0" maskUnits="userSpaceOnUse" x="0" y="0" width="24" height="24"><rect width="24" height="24" fill="#fff"/><g fill="#000"><rect x="7.2" y="5.2" width="15.2" height="17.6" rx="2.8"/></g></mask></defs><g mask="url(#__ID__0)"><rect x="3" y="2.6" width="12.4" height="14.8" rx="1.4"/></g><g><rect x="8.6" y="6.6" width="12.4" height="14.8" rx="1.4"/></g>' };
const i_cross: IconDef = { viewBox: '0 0 24 24', body: '<g><g transform="rotate(45 12 12)"><rect x="10.5" y="3.2" width="3" height="17.6" rx=".8"/></g><g transform="rotate(-45 12 12)"><rect x="10.5" y="3.2" width="3" height="17.6" rx=".8"/></g></g>' };
const i_dice: IconDef = { viewBox: '0 0 24 24', body: '<defs><mask id="__ID__0" maskUnits="userSpaceOnUse" x="0" y="0" width="24" height="24"><rect width="24" height="24" fill="#fff"/><g fill="#000"><circle cx="7.8" cy="7.8" r="1.7"/><circle cx="12" cy="12" r="1.7"/><circle cx="16.2" cy="16.2" r="1.7"/><circle cx="16.2" cy="7.8" r="1.7"/><circle cx="7.8" cy="16.2" r="1.7"/></g></mask></defs><g mask="url(#__ID__0)"><rect x="3" y="3" width="18" height="18" rx="3"/></g>' };
const i_dismantle: IconDef = { viewBox: '0 0 24 24', body: '<defs><mask id="__ID__0" maskUnits="userSpaceOnUse" x="0" y="0" width="24" height="24"><rect width="24" height="24" fill="#fff"/><g fill="#000"><path d="M12.6 0 10.6 5.2l2.4 3.4-2.6 4 2.6 3.6-1.8 4.4L12 24H24V0z"/></g></mask><mask id="__ID__1" maskUnits="userSpaceOnUse" x="0" y="0" width="24" height="24"><rect width="24" height="24" fill="#fff"/><g fill="#000"><path d="M13.9 0 11.9 5.2l2.4 3.4-2.6 4 2.6 3.6-1.8 4.4.8 3.4H0V0z"/></g></mask></defs><g><rect x="1.5" y="20" width="21" height="2" rx=".6"/></g><g mask="url(#__ID__0)"><path d="M2.4 11 12 3.2l9.6 7.8z"/><rect x="4.8" y="12.2" width="14.4" height="8.8"/></g><g transform="rotate(9 19.2 20)"><g mask="url(#__ID__1)"><path d="M2.4 11 12 3.2l9.6 7.8z"/><rect x="4.8" y="12.2" width="14.4" height="8.8"/></g></g>' };
const i_eject: IconDef = { viewBox: '0 0 24 24', body: '<defs><mask id="__ID__0" maskUnits="userSpaceOnUse" x="0" y="0" width="24" height="24"><rect width="24" height="24" fill="#fff"/><g fill="#000"><rect x="5" y="5.4" width="6.4" height="16.4" rx=".6"/><path d="M8.6 9.4h8.2v-3.7l6.6 6.3-6.6 6.3v-3.7H8.6z" stroke="#000" stroke-width="2.6" stroke-linejoin="round"/></g></mask></defs><g mask="url(#__ID__0)"><path d="M2.6 21.4V5a2 2 0 0 1 2-2h7.2a2 2 0 0 1 2 2v16.4z"/></g><g><path d="M8.6 10.8h8.2V7.1l5.6 4.9-5.6 4.9v-3.7H8.6z"/></g>' };
const i_emblem: IconDef = { viewBox: '0 0 24 24', body: '<defs><mask id="__ID__0" maskUnits="userSpaceOnUse" x="0" y="0" width="24" height="24"><rect width="24" height="24" fill="#fff"/><g fill="#000"><circle cx="12" cy="12" r="1.5"/></g></mask></defs><g mask="url(#__ID__0)"><path d="M12 1.6 13.9 10.1 22.4 12 13.9 13.9 12 22.4 10.1 13.9 1.6 12 10.1 10.1z"/><path d="M12 12 18.3 5.7 14.6 12z M12 12 18.3 18.3 12 14.6z M12 12 5.7 18.3 9.4 12z M12 12 5.7 5.7 12 9.4z"/></g>' };
const i_error: IconDef = { viewBox: '0 0 24 24', body: '<defs><mask id="__ID__0" maskUnits="userSpaceOnUse" x="0" y="0" width="24" height="24"><rect width="24" height="24" fill="#fff"/><g fill="#000"><path d="M10.8 5.8h2.4l-.4 8.4h-1.6z"/><circle cx="12" cy="17.4" r="1.45"/></g></mask></defs><g mask="url(#__ID__0)"><path d="M8.11 2.6L15.89 2.6L21.4 8.11L21.4 15.89L15.89 21.4L8.11 21.4L2.6 15.89L2.6 8.11z" stroke="currentColor" stroke-width="1.2" stroke-linejoin="round"/></g>' };
const i_eye: IconDef = { viewBox: '0 0 24 24', body: '<defs><mask id="__ID__0" maskUnits="userSpaceOnUse" x="0" y="0" width="24" height="24"><rect width="24" height="24" fill="#fff"/><g fill="#000"><circle cx="12" cy="12" r="4.4"/></g></mask></defs><g mask="url(#__ID__0)"><path d="M1.6 12Q6.4 4.6 12 4.6T22.4 12Q17.6 19.4 12 19.4T1.6 12z"/></g><g><circle cx="12" cy="12" r="2.2"/></g>' };
const i_fast_forward: IconDef = { viewBox: '0 0 24 24', body: '<g><path d="M3 5.6 11.6 12 3 18.4z" stroke="currentColor" stroke-width="1.2" stroke-linejoin="round"/><path d="M12.2 5.6 20.8 12l-8.6 6.4z" stroke="currentColor" stroke-width="1.2" stroke-linejoin="round"/></g>' };
const i_fence: IconDef = { viewBox: '0 0 24 24', body: '<g><rect x="1.5" y="20" width="21" height="2" rx=".6"/><path d="M2.6 20V7.6l1.9-2.8 1.9 2.8V20z"/><path d="M7.6 20V7.6l1.9-2.8 1.9 2.8V20z"/><path d="M12.6 20V7.6l1.9-2.8 1.9 2.8V20z"/><path d="M17.6 20V7.6l1.9-2.8 1.9 2.8V20z"/><rect x="1.6" y="10" width="20.8" height="2.2" rx=".5"/><rect x="1.6" y="15" width="20.8" height="2.2" rx=".5"/></g>' };
const i_flag: IconDef = { viewBox: '0 0 24 24', body: '<defs><mask id="__ID__0" maskUnits="userSpaceOnUse" x="0" y="0" width="24" height="24"><rect width="24" height="24" fill="#fff"/><g fill="#000"><path d="M8.6 5.2h7.4l-1.4 2 1.4 2H8.6z"/></g></mask></defs><g mask="url(#__ID__0)"><rect x="4.6" y="2.4" width="2" height="19.2" rx=".6"/><path d="M6.6 3.2h13l-2.8 4 2.8 4h-13z"/></g>' };
const i_forge: IconDef = { viewBox: '0 0 24 24', body: '<defs><mask id="__ID__0" maskUnits="userSpaceOnUse" x="0" y="0" width="24" height="24"><rect width="24" height="24" fill="#fff"/><g fill="#000"><path d="M10.2 20q1.9-2.8 3.8-2.8t3.8 2.8z"/></g></mask></defs><g mask="url(#__ID__0)"><rect x="1.5" y="20" width="21" height="2" rx=".6"/><path d="M2.4 7.4 7.6 6.8h13v3.4h-2.8q-2.1.4-2.4 2.6v1.8q2.4.4 4.2 2.4V20H6.2v-3q1.8-2 4.4-2.4v-1.8q-.3-2.2-2.4-2.6Q4.6 9.8 2.4 7.4z"/></g>' };
const i_fullscreen: IconDef = { viewBox: '0 0 24 24', body: '<g><path d="M3 9.4V3h6.4v2.3H5.3v4.1zM14.6 3H21v6.4h-2.3V5.3h-4.1zM3 14.6V21h6.4v-2.3H5.3v-4.1zM21 14.6V21h-6.4v-2.3h4.1v-4.1z"/></g>' };
const i_gate: IconDef = { viewBox: '0 0 24 24', body: '<defs><mask id="__ID__0" maskUnits="userSpaceOnUse" x="0" y="0" width="24" height="24"><rect width="24" height="24" fill="#fff"/><g fill="#000"><path d="M12 6v14" fill="none" stroke="#000" stroke-width="1.3" stroke-linecap="butt" stroke-linejoin="round"/></g></mask></defs><g mask="url(#__ID__0)"><rect x="1.5" y="20" width="21" height="2" rx=".6"/><rect x="2.6" y="9" width="3" height="11"/><rect x="18.4" y="9" width="3" height="11"/><path d="M2.6 10A9.4 6.6 0 0 1 21.4 10h-2.2A7.2 4.4 0 0 0 4.8 10z"/><path d="M7 20v-9.4a5 3.4 0 0 1 10 0V20z"/></g>' };
const i_gold_vein: IconDef = { viewBox: '0 0 24 24', body: '<defs><mask id="__ID__0" maskUnits="userSpaceOnUse" x="0" y="0" width="24" height="24"><rect width="24" height="24" fill="#fff"/><g fill="#000"><path d="M12.4 10.4Q13.24 13.76 16.6 14.6Q13.24 15.44 12.4 18.8Q11.56 15.44 8.2 14.6Q11.56 13.76 12.4 10.4z"/><circle cx="6.8" cy="17" r="1.1"/><circle cx="17.6" cy="13.6" r="1.1"/></g></mask></defs><g mask="url(#__ID__0)"><rect x="1.5" y="20" width="21" height="2" rx=".6"/><path d="M2.6 20.4 4.2 13.6 8 9.4l3.2 1.2 3.4-4.8 4.2 3.4 2.6 6.4v4.8z"/></g>' };
const i_gold: IconDef = { viewBox: '0 0 24 24', body: '<defs><mask id="__ID__0" maskUnits="userSpaceOnUse" x="0" y="0" width="24" height="24"><rect width="24" height="24" fill="#fff"/><g fill="#000"><circle cx="14.6" cy="14.6" r="8.5"/></g></mask><mask id="__ID__1" maskUnits="userSpaceOnUse" x="0" y="0" width="24" height="24"><rect width="24" height="24" fill="#fff"/><g fill="#000"><circle cx="14.6" cy="14.6" r="5.5" fill="none" stroke="#000" stroke-width="1.3"/><path transform="translate(14.6 14.6)" d="M0 -3.6 1 -1 3.6 0 1 1 0 3.6 -1 1 -3.6 0 -1 -1z"/></g></mask></defs><g mask="url(#__ID__0)"><circle cx="9" cy="9" r="6.8"/></g><g mask="url(#__ID__1)"><circle cx="14.6" cy="14.6" r="7.2"/></g>' };
const i_hold: IconDef = { viewBox: '0 0 24 24', body: '<defs><mask id="__ID__0" maskUnits="userSpaceOnUse" x="0" y="0" width="24" height="24"><rect width="24" height="24" fill="#fff"/><g fill="#000"><path d="M12.7 5.6h4.7v5.6c0 3.6-2.2 6.4-4.7 8z"/></g></mask></defs><g mask="url(#__ID__0)"><path d="M4.4 3.4h15.2v7.8c0 5-3.6 8.6-7.6 10.6-4-2-7.6-5.6-7.6-10.6z"/></g>' };
const i_house: IconDef = { viewBox: '0 0 24 24', body: '<defs><mask id="__ID__0" maskUnits="userSpaceOnUse" x="0" y="0" width="24" height="24"><rect width="24" height="24" fill="#fff"/><g fill="#000"><rect x="10.5" y="14.6" width="3" height="5.4"/></g></mask></defs><g mask="url(#__ID__0)"><rect x="1.5" y="20" width="21" height="2" rx=".6"/><path d="M2.4 11 12 3.2l9.6 7.8z"/><rect x="15.4" y="4.2" width="2.4" height="5"/><rect x="4.8" y="12.2" width="14.4" height="8.8"/></g>' };
const i_idle_worker: IconDef = { viewBox: '0 0 24 24', body: '<defs><mask id="__ID__0" maskUnits="userSpaceOnUse" x="0" y="0" width="24" height="24"><rect width="24" height="24" fill="#fff"/><g fill="#000"><path d="M3.4 9.6h14.4" stroke="#000" stroke-width="1.1"/></g></mask></defs><g mask="url(#__ID__0)"><circle cx="10.6" cy="11.4" r="3.3"/><path d="M3 21.6v-2.2a7.6 5.8 0 0 1 15.2 0v2.2z"/><ellipse cx="10.6" cy="8" rx="7.2" ry="1.55"/><path d="M7.4 8.2 8.1 4.1q2.5-1.2 5 0l.7 4.1z"/><path d="M16.6 2.6h4.6l-4.6 4.8h4.6" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="square" stroke-linejoin="round"/></g>' };
const i_import: IconDef = { viewBox: '0 0 24 24', body: '<g><path d="M12 2.4l4.6 4.8h-3.4v9.4h-2.4V7.2H7.4z"/><path d="M3 14.6h2.4v4.2h13.2v-4.2H21v6.6H3z"/></g>' };
const i_info: IconDef = { viewBox: '0 0 24 24', body: '<defs><mask id="__ID__0" maskUnits="userSpaceOnUse" x="0" y="0" width="24" height="24"><rect width="24" height="24" fill="#fff"/><g fill="#000"><circle cx="12.4" cy="7" r="1.6"/><path d="M9.6 10.2h3.9v6.5h1.6v1.7H9.6v-1.7h1.6v-4.8H9.6z"/></g></mask></defs><g mask="url(#__ID__0)"><circle cx="12" cy="12" r="10"/></g>' };
const i_like: IconDef = { viewBox: '0 0 24 24', body: '<g><path d="M12 21L3.63 12.18A5.2 5.2 0 1 1 12 6.18A5.2 5.2 0 1 1 20.37 12.18z"/></g>' };
const i_link: IconDef = { viewBox: '0 0 24 24', body: '<g><g transform="rotate(-45 12 12)"><path d="M6.6 9.2h3.2a2.8 2.8 0 0 1 0 5.6H6.6a2.8 2.8 0 0 1 0-5.6zM14.2 9.2h3.2a2.8 2.8 0 0 1 0 5.6h-3.2a2.8 2.8 0 0 1 0-5.6z" fill="none" stroke="currentColor" stroke-width="2.3" stroke-linecap="round" stroke-linejoin="round"/><rect x="9.6" y="10.9" width="4.8" height="2.2" rx="1.1"/></g></g>' };
const i_lock: IconDef = { viewBox: '0 0 24 24', body: '<defs><mask id="__ID__0" maskUnits="userSpaceOnUse" x="0" y="0" width="24" height="24"><rect width="24" height="24" fill="#fff"/><g fill="#000"><circle cx="12" cy="14.8" r="1.7"/><rect x="11.25" y="15" width="1.5" height="3.8" rx=".5"/></g></mask></defs><g mask="url(#__ID__0)"><path d="M8 11V7.6a4 4 0 0 1 8 0V11" fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="butt" stroke-linejoin="round"/><rect x="4.8" y="10.4" width="14.4" height="11.2" rx="1.4"/></g>' };
const i_map_editor: IconDef = { viewBox: '0 0 24 24', body: '<defs><mask id="__ID__0" maskUnits="userSpaceOnUse" x="0" y="0" width="24" height="24"><rect width="24" height="24" fill="#fff"/><g fill="#000"><circle cx="12" cy="5" r="1.1"/></g></mask></defs><g mask="url(#__ID__0)"><circle cx="12" cy="5" r="3"/><rect x="11.1" y="1" width="1.8" height="2.4" rx=".4"/><path d="M10.9 7.4 4.6 21.6" fill="none" stroke="currentColor" stroke-width="2.3" stroke-linecap="butt" stroke-linejoin="round"/><path d="M13.1 7.4l4.4 10" fill="none" stroke="currentColor" stroke-width="2.3" stroke-linecap="butt" stroke-linejoin="round"/><path d="M16.2 16.6l2.7-1.2 1.9 4.2-1.5 2.6-.4-.2-1.3-1.2z"/></g>' };
const i_menu: IconDef = { viewBox: '0 0 24 24', body: '<g><rect x="3" y="4.6" width="18" height="2.6" rx=".7"/><rect x="3" y="10.7" width="18" height="2.6" rx=".7"/><rect x="3" y="16.8" width="18" height="2.6" rx=".7"/></g>' };
const i_militia: IconDef = { viewBox: '0 0 24 24', body: '<g><g transform="rotate(38 12 12)"><rect x="11" y="9.6" width="2" height="13.6" rx=".7"/><path d="M6.6 8.4a1 1 0 0 1 1-1h8.8a1 1 0 0 1 1 1v2.4H6.6z"/><path d="M6.6 8.4V3.6l.9-2 .9 2v4.8zM11.1 8.4V2.8l.9-2 .9 2v5.6zM15.6 8.4V3.6l.9-2 .9 2v4.8z"/></g></g>' };
const i_mine: IconDef = { viewBox: '0 0 24 24', body: '<defs><mask id="__ID__0" maskUnits="userSpaceOnUse" x="0" y="0" width="24" height="24"><rect width="24" height="24" fill="#fff"/><g fill="#000"><path d="M8.6 20v-4.4h6.8V20h-1.4v-3h-4v3z"/></g></mask></defs><g mask="url(#__ID__0)"><rect x="1.5" y="20" width="21" height="2" rx=".6"/><path d="M2.4 21q1-9.6 9.6-10.6 8.6 1 9.6 10.6z"/></g><g><g transform="rotate(45 12 6)"><rect x="11.2" y="2.6" width="1.6" height="8.2" rx=".5"/><rect x="9" y="1.2" width="6" height="2.6" rx=".5"/></g><g transform="rotate(-45 12 6)"><rect x="11.2" y="2.6" width="1.6" height="8.2" rx=".5"/><path d="M8.6 2.6 12 1.2l3.4 1.4v1.4H8.6z"/></g></g>' };
const i_minus: IconDef = { viewBox: '0 0 24 24', body: '<g><rect x="3.6" y="10.8" width="16.8" height="2.4" rx=".6"/></g>' };
const i_multiplayer: IconDef = { viewBox: '0 0 24 24', body: '<defs><mask id="__ID__0" maskUnits="userSpaceOnUse" x="0" y="0" width="24" height="24"><rect width="24" height="24" fill="#fff"/><g fill="#000"><ellipse cx="12" cy="12" rx="4.2" ry="9.8" fill="none" stroke="#000" stroke-width="1.3"/><path d="M12 2v20M2.4 12h19.2M3.8 7.4h16.4M3.8 16.6h16.4" stroke="#000" stroke-width="1.3"/></g></mask></defs><g mask="url(#__ID__0)"><circle cx="12" cy="12" r="9.8"/></g>' };
const i_new: IconDef = { viewBox: '0 0 24 24', body: '<g><path d="M10 5.6Q11.6 12 18 13.6Q11.6 15.2 10 21.6Q8.4 15.2 2 13.6Q8.4 12 10 5.6z"/><path d="M18.4 1.8Q19.26 4.54 22 5.4Q19.26 6.26 18.4 9Q17.54 6.26 14.8 5.4Q17.54 4.54 18.4 1.8z"/></g>' };
const i_patrol: IconDef = { viewBox: '0 0 24 24', body: '<g><rect x="3" y="6.5" width="3.6" height="2.4" rx=".5"/><rect x="8" y="6.5" width="6.4" height="2.4" rx=".5"/><path d="M14 3.2l6.4 4.5L14 12.2z"/><rect x="17.4" y="15.1" width="3.6" height="2.4" rx=".5"/><rect x="9.6" y="15.1" width="6.4" height="2.4" rx=".5"/><path d="M10 11.8l-6.4 4.5 6.4 4.5z"/></g>' };
const i_pause: IconDef = { viewBox: '0 0 24 24', body: '<g><rect x="5.4" y="4" width="4.6" height="16" rx=".8"/><rect x="14" y="4" width="4.6" height="16" rx=".8"/></g>' };
const i_pencil: IconDef = { viewBox: '0 0 24 24', body: '<g><g transform="rotate(45 12 12)"><rect x="9.8" y="5" width="4.4" height="12.4"/><path d="M9.8 17.4h4.4L12 22z"/><rect x="9.8" y="1.6" width="4.4" height="2.4" rx=".6"/></g></g>' };
const i_pin: IconDef = { viewBox: '0 0 24 24', body: '<defs><mask id="__ID__0" maskUnits="userSpaceOnUse" x="0" y="0" width="24" height="24"><rect width="24" height="24" fill="#fff"/><g fill="#000"><circle cx="10.4" cy="5.8" r="1.4"/></g></mask></defs><g mask="url(#__ID__0)"><circle cx="12" cy="7.4" r="5.2"/><path d="M11 12h2l-.6 10h-.8z"/></g>' };
const i_play_game: IconDef = { viewBox: '0 0 24 24', body: '<defs><mask id="__ID__0" maskUnits="userSpaceOnUse" x="0" y="0" width="24" height="24"><rect width="24" height="24" fill="#fff"/><g fill="#000"><circle cx="12" cy="12" r="6.7" fill="none" stroke="#000" stroke-width="1.2"/><path d="M9.9 8.2 16 12l-6.1 3.8z"/></g></mask></defs><g mask="url(#__ID__0)"><circle cx="12" cy="12" r="8"/><circle cx="20" cy="12" r="1.9"/><circle cx="18.93" cy="16" r="1.9"/><circle cx="16" cy="18.93" r="1.9"/><circle cx="12" cy="20" r="1.9"/><circle cx="8" cy="18.93" r="1.9"/><circle cx="5.07" cy="16" r="1.9"/><circle cx="4" cy="12" r="1.9"/><circle cx="5.07" cy="8" r="1.9"/><circle cx="8" cy="5.07" r="1.9"/><circle cx="12" cy="4" r="1.9"/><circle cx="16" cy="5.07" r="1.9"/><circle cx="18.93" cy="8" r="1.9"/></g>' };
const i_play: IconDef = { viewBox: '0 0 24 24', body: '<g><path d="M6.5 3.6a1 1 0 0 1 1.5-.86l12.6 8.4a1 1 0 0 1 0 1.72L8 21.26A1 1 0 0 1 6.5 20.4z"/></g>' };
const i_plus: IconDef = { viewBox: '0 0 24 24', body: '<g><rect x="10.8" y="3.6" width="2.4" height="16.8" rx=".6"/><rect x="3.6" y="10.8" width="16.8" height="2.4" rx=".6"/></g>' };
const i_population: IconDef = { viewBox: '0 0 24 24', body: '<defs><mask id="__ID__0" maskUnits="userSpaceOnUse" x="0" y="0" width="24" height="24"><rect width="24" height="24" fill="#fff"/><g fill="#000"><circle cx="15.4" cy="8.9" r="4.4" fill="#000"/><path d="M7.6 22.4v-3.6a7.8 6.6 0 0 1 15.6 0v3.6z" fill="#000"/></g></mask></defs><g mask="url(#__ID__0)"><circle cx="8.3" cy="7.4" r="3.1"/><path d="M2.4 20v-3.96a5.8 5.46 0 0 1 11.6 0v3.96z"/></g><g><circle cx="15.4" cy="8.9" r="3.5"/><path d="M8.8 21.5v-4a6.6 5.52 0 0 1 13.2 0v4.01z"/></g>' };
const i_rally: IconDef = { viewBox: '0 0 24 24', body: '<g><rect x="5.4" y="2.4" width="2" height="17.4" rx=".6"/><path d="M7.4 3h12.2l-2.8 3.9 2.8 3.9H7.4z"/><ellipse cx="6.4" cy="20.4" rx="4.4" ry="1.6"/></g>' };
const i_range: IconDef = { viewBox: '0 0 24 24', body: '<g><path d="M6.4 3.2q11.6 8.8 0 17.6" fill="none" stroke="currentColor" stroke-width="2.6" stroke-linecap="butt" stroke-linejoin="round"/><path d="M6.4 3.4v17.2" fill="none" stroke="currentColor" stroke-width="1.2" stroke-linecap="butt" stroke-linejoin="round"/><path d="M3.4 12h13.4" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="butt" stroke-linejoin="round"/><path d="M15.8 8.8 21.6 12l-5.8 3.2z"/><path d="M2.4 9.8l3 2.2-3 2.2z"/></g>' };
const i_ranked: IconDef = { viewBox: '0 0 24 24', body: '<g><path d="M4 8L12 3l8 5v2.4l-8-5-8 5z"/><path d="M4 13.2L12 8.2l8 5v2.4l-8-5-8 5z"/><path d="M4 18.4L12 13.4l8 5v2.4l-8-5-8 5z"/></g>' };
const i_redo: IconDef = { viewBox: '0 0 24 24', body: '<g transform="matrix(-1 0 0 1 24 0)"><g><path d="M8 8.6h6.4a5.4 5.4 0 0 1 0 10.8H7.6" fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="butt" stroke-linejoin="round"/><path d="M2.6 8.6 8.6 3.4v10.4z"/></g></g>' };
const i_replay: IconDef = { viewBox: '0 0 24 24', body: '<g><path d="M6.1 7.2A7.8 7.8 0 1 1 4.2 13" fill="none" stroke="currentColor" stroke-width="2.3" stroke-linecap="butt" stroke-linejoin="round"/><path d="M2.4 3.6 9 4.6 4.4 9.6z"/><path d="M10 8.3l6 3.7-6 3.7z"/></g>' };
const i_resize: IconDef = { viewBox: '0 0 24 24', body: '<g><rect x="3" y="12" width="9" height="9" rx="1"/><path d="M13.4 3.6h7v7" fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="butt" stroke-linejoin="round"/><g transform="rotate(-45 15.2 8.8)"><rect x="12.4" y="7.7" width="3.4" height="2.2"/><path d="M15 5.6l4.4 3.2-4.4 3.2z"/></g></g>' };
const i_rotate_device: IconDef = { viewBox: '0 0 24 24', body: '<defs><mask id="__ID__0" maskUnits="userSpaceOnUse" x="0" y="0" width="24" height="24"><rect width="24" height="24" fill="#fff"/><g fill="#000"><rect x="4.4" y="7.2" width="5.6" height="10.4" rx=".4"/></g></mask></defs><g mask="url(#__ID__0)"><rect x="2.6" y="5" width="9.2" height="16" rx="1.8"/></g><g><path d="M13.6 4.8a5.8 5.8 0 0 1 5.8 5.8" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="butt" stroke-linejoin="round"/><path d="M16.8 10.2h5.2l-2.6 4.2z"/></g>' };
const i_save: IconDef = { viewBox: '0 0 24 24', body: '<g><path d="M10.8 2.6h2.4v9.2h3.4L12 16.6l-4.6-4.8h3.4z"/><path d="M3 14.6h2.4v4.2h13.2v-4.2H21v6.6H3z"/></g>' };
const i_settings: IconDef = { viewBox: '0 0 24 24', body: '<defs><mask id="__ID__0" maskUnits="userSpaceOnUse" x="0" y="0" width="24" height="24"><rect width="24" height="24" fill="#fff"/><g fill="#000"><circle cx="12" cy="12" r="3"/></g></mask></defs><g mask="url(#__ID__0)"><circle cx="12" cy="12" r="7"/><g transform="rotate(0 12 12)"><rect x="10.3" y="1.6" width="3.4" height="4.6" rx=".6"/></g><g transform="rotate(45 12 12)"><rect x="10.3" y="1.6" width="3.4" height="4.6" rx=".6"/></g><g transform="rotate(90 12 12)"><rect x="10.3" y="1.6" width="3.4" height="4.6" rx=".6"/></g><g transform="rotate(135 12 12)"><rect x="10.3" y="1.6" width="3.4" height="4.6" rx=".6"/></g><g transform="rotate(180 12 12)"><rect x="10.3" y="1.6" width="3.4" height="4.6" rx=".6"/></g><g transform="rotate(225 12 12)"><rect x="10.3" y="1.6" width="3.4" height="4.6" rx=".6"/></g><g transform="rotate(270 12 12)"><rect x="10.3" y="1.6" width="3.4" height="4.6" rx=".6"/></g><g transform="rotate(315 12 12)"><rect x="10.3" y="1.6" width="3.4" height="4.6" rx=".6"/></g></g>' };
const i_shape_round: IconDef = { viewBox: '0 0 24 24', body: '<g><circle cx="12" cy="12" r="8"/></g>' };
const i_speed: IconDef = { viewBox: '0 0 24 24', body: '<defs><mask id="__ID__0" maskUnits="userSpaceOnUse" x="0" y="0" width="24" height="24"><rect width="24" height="24" fill="#fff"/><g fill="#000"><path d="M4.6 18.2h16.2" stroke="#000" stroke-width="1.2"/></g></mask></defs><g mask="url(#__ID__0)"><path d="M7.8 3h6.4v9.6l5.4 3.2a2 2 0 0 1 1 1.7V20H4.6v-3.4l3.2-1.6z"/></g>' };
const i_stop: IconDef = { viewBox: '0 0 24 24', body: '<g><rect x="4.6" y="4.6" width="14.8" height="14.8" rx="1.6"/></g>' };
const i_sword: IconDef = { viewBox: '0 0 24 24', body: '<g><g transform="rotate(45 12 12)"><path d="M10.8 15.2V4.4L12 2l1.2 2.4v10.8z"/><rect x="7.6" y="15" width="8.8" height="2" rx=".6"/><rect x="11.05" y="16.6" width="1.9" height="3.6"/><circle cx="12" cy="21.3" r="1.45"/></g></g>' };
const i_sym_none: IconDef = { viewBox: '0 0 24 24', body: '<g><g transform="translate(12 12) scale(1.6) translate(-6.4 -6.6)"><rect x="2.6" y="2.6" width="2.2" height="8" rx=".5"/><path d="M4.8 2.6l5.4 2.8-5.4 2.8z"/></g></g>' };
const i_sym_rot: IconDef = { viewBox: '0 0 24 24', body: '<g><rect x="2.6" y="2.6" width="2.2" height="8" rx=".5"/><path d="M4.8 2.6l5.4 2.8-5.4 2.8z"/><g transform="rotate(180 12 12)"><rect x="2.6" y="2.6" width="2.2" height="8" rx=".5"/><path d="M4.8 2.6l5.4 2.8-5.4 2.8z"/></g><circle cx="12" cy="12" r="1.8"/></g>' };
const i_sym_rot4: IconDef = { viewBox: '0 0 24 24', body: '<g><rect x="2.6" y="2.6" width="2.2" height="8" rx=".5"/><path d="M4.8 2.6l5.4 2.8-5.4 2.8z"/><g transform="rotate(90 12 12)"><rect x="2.6" y="2.6" width="2.2" height="8" rx=".5"/><path d="M4.8 2.6l5.4 2.8-5.4 2.8z"/></g><g transform="rotate(180 12 12)"><rect x="2.6" y="2.6" width="2.2" height="8" rx=".5"/><path d="M4.8 2.6l5.4 2.8-5.4 2.8z"/></g><g transform="rotate(270 12 12)"><rect x="2.6" y="2.6" width="2.2" height="8" rx=".5"/><path d="M4.8 2.6l5.4 2.8-5.4 2.8z"/></g><circle cx="12" cy="12" r="1.8"/></g>' };
const i_sym_x: IconDef = { viewBox: '0 0 24 24', body: '<g><rect x="2.6" y="2.6" width="2.2" height="8" rx=".5"/><path d="M4.8 2.6l5.4 2.8-5.4 2.8z"/><g transform="matrix(-1 0 0 1 24 0)"><rect x="2.6" y="2.6" width="2.2" height="8" rx=".5"/><path d="M4.8 2.6l5.4 2.8-5.4 2.8z"/></g><rect x="11.3" y="2" width="1.4" height="3.2" rx=".3"/><rect x="11.3" y="6.2" width="1.4" height="3.2" rx=".3"/><rect x="11.3" y="10.4" width="1.4" height="3.2" rx=".3"/><rect x="11.3" y="14.6" width="1.4" height="3.2" rx=".3"/><rect x="11.3" y="18.8" width="1.4" height="3.2" rx=".3"/></g>' };
const i_sym_xy: IconDef = { viewBox: '0 0 24 24', body: '<g><rect x="2.6" y="2.6" width="2.2" height="8" rx=".5"/><path d="M4.8 2.6l5.4 2.8-5.4 2.8z"/><g transform="matrix(-1 0 0 1 24 0)"><rect x="2.6" y="2.6" width="2.2" height="8" rx=".5"/><path d="M4.8 2.6l5.4 2.8-5.4 2.8z"/></g><g transform="matrix(1 0 0 -1 0 24)"><rect x="2.6" y="2.6" width="2.2" height="8" rx=".5"/><path d="M4.8 2.6l5.4 2.8-5.4 2.8z"/></g><g transform="rotate(180 12 12)"><rect x="2.6" y="2.6" width="2.2" height="8" rx=".5"/><path d="M4.8 2.6l5.4 2.8-5.4 2.8z"/></g><rect x="11.3" y="2" width="1.4" height="3.2" rx=".3"/><rect x="11.3" y="6.2" width="1.4" height="3.2" rx=".3"/><rect x="11.3" y="10.4" width="1.4" height="3.2" rx=".3"/><rect x="11.3" y="14.6" width="1.4" height="3.2" rx=".3"/><rect x="11.3" y="18.8" width="1.4" height="3.2" rx=".3"/><rect x="2" y="11.3" width="3.2" height="1.4" rx=".3"/><rect x="6.2" y="11.3" width="3.2" height="1.4" rx=".3"/><rect x="10.4" y="11.3" width="3.2" height="1.4" rx=".3"/><rect x="14.6" y="11.3" width="3.2" height="1.4" rx=".3"/><rect x="18.8" y="11.3" width="3.2" height="1.4" rx=".3"/></g>' };
const i_sym_y: IconDef = { viewBox: '0 0 24 24', body: '<g><rect x="2.6" y="2.6" width="2.2" height="8" rx=".5"/><path d="M4.8 2.6l5.4 2.8-5.4 2.8z"/><g transform="matrix(1 0 0 -1 0 24)"><rect x="2.6" y="2.6" width="2.2" height="8" rx=".5"/><path d="M4.8 2.6l5.4 2.8-5.4 2.8z"/></g><rect x="2" y="11.3" width="3.2" height="1.4" rx=".3"/><rect x="6.2" y="11.3" width="3.2" height="1.4" rx=".3"/><rect x="10.4" y="11.3" width="3.2" height="1.4" rx=".3"/><rect x="14.6" y="11.3" width="3.2" height="1.4" rx=".3"/><rect x="18.8" y="11.3" width="3.2" height="1.4" rx=".3"/></g>' };
const i_take_slot: IconDef = { viewBox: '0 0 24 24', body: '<g><path d="M12.6 3h6.8a1.6 1.6 0 0 1 1.6 1.6v14.8a1.6 1.6 0 0 1-1.6 1.6h-6.8v-2.4h6V5.4h-6z"/><rect x="2.6" y="10.8" width="8.6" height="2.4" rx=".6"/><path d="M10 6.2 15.8 12 10 17.8z"/></g>' };
const i_tier_bronze: IconDef = { viewBox: '0 0 24 24', body: '<defs><mask id="__ID__0" maskUnits="userSpaceOnUse" x="0" y="0" width="24" height="24"><rect width="24" height="24" fill="#fff"/><g fill="#000"><rect x="11" y="16.4" width="2" height="3.6"/></g></mask></defs><g mask="url(#__ID__0)"><rect x="5.6" y="20" width="12.8" height="2" rx=".6"/><path d="M8 20L8 14.4L7.2 14.4L12 9.2L16.8 14.4L16 14.4L16 20z"/></g>' };
const i_tier_diamond: IconDef = { viewBox: '0 0 24 24', body: '<defs><mask id="__ID__0" maskUnits="userSpaceOnUse" x="0" y="0" width="24" height="24"><rect width="24" height="24" fill="#fff"/><g fill="#000"><path d="M10.6 20v-2.6a1.4 1.4 0 0 1 2.8 0V20z"/><rect x="6.4" y="12.4" width="11.2" height="1.3"/></g></mask></defs><g mask="url(#__ID__0)"><rect x="1.5" y="20" width="21" height="2" rx=".6"/><path d="M2.4 20L2.4 10.4L2 10.4L4.4 5L6.8 10.4L6.4 10.4L6.4 20z"/><path d="M17.6 20L17.6 10.4L17.2 10.4L19.6 5L22 10.4L21.6 10.4L21.6 20z"/><rect x="6.4" y="13.6" width="11.2" height="6.4"/><rect x="9.8" y="8.4" width="4.4" height="5.6"/><path d="M12 2.4C12.68 4.08 15.91 4.68 15.4 7.08Q15.06 8.4 12 8.4Q8.94 8.4 8.6 7.08C8.09 4.68 11.32 4.08 12 2.4z"/><rect x="11.3" y="1.4" width="1.4" height="2"/></g>' };
const i_tier_gold: IconDef = { viewBox: '0 0 24 24', body: '<defs><mask id="__ID__0" maskUnits="userSpaceOnUse" x="0" y="0" width="24" height="24"><rect width="24" height="24" fill="#fff"/><g fill="#000"><rect x="11.3" y="12" width="1.4" height="3"/></g></mask></defs><g mask="url(#__ID__0)"><rect x="1.5" y="20" width="21" height="2" rx=".6"/><path d="M2.8 20L2.8 14.4L2.3 14.4L5.7 10.4L9.1 14.4L8.6 14.4L8.6 20z"/><path d="M15.4 20L15.4 14.4L14.9 14.4L18.3 10.4L21.7 14.4L21.2 14.4L21.2 20z"/><rect x="10.2" y="9.2" width="3.6" height="11"/><path d="M9.8 9.6 12 2.4l2.2 7.2z"/></g>' };
const i_tier_grandmaster: IconDef = { viewBox: '0 0 24 24', body: '<defs><mask id="__ID__0" maskUnits="userSpaceOnUse" x="0" y="0" width="24" height="24"><rect width="24" height="24" fill="#fff"/><g fill="#000"><path d="M10.7 20v-2.4a1.3 1.3 0 0 1 2.6 0V20z"/><rect x="8" y="7.8" width="8" height="1.2"/></g></mask></defs><g mask="url(#__ID__0)"><rect x="1.5" y="20" width="21" height="2" rx=".6"/><path d="M1.6 20L1.6 10.6L1.3 10.6L3.2 3.6L5.1 10.6L4.8 10.6L4.8 20z"/><path d="M19.2 20L19.2 10.6L18.9 10.6L20.8 3.6L22.7 10.6L22.4 10.6L22.4 20z"/><path d="M5.8 20L5.8 13.4L5.5 13.4L7.1 8.6L8.7 13.4L8.4 13.4L8.4 20z"/><path d="M15.6 20L15.6 13.4L15.3 13.4L16.9 8.6L18.5 13.4L18.2 13.4L18.2 20z"/><rect x="9.4" y="9" width="5.2" height="11"/><rect x="4" y="15.4" width="16" height="4.6"/><path d="M8.2 8L8.2 2.5L10.1 4.85L12 2.5L13.9 4.85L15.8 2.5L15.8 8z"/><circle cx="8.2" cy="2.5" r="1.1"/><circle cx="12" cy="2.5" r="1.1"/><circle cx="15.8" cy="2.5" r="1.1"/></g>' };
const i_tier_master: IconDef = { viewBox: '0 0 24 24', body: '<defs><mask id="__ID__0" maskUnits="userSpaceOnUse" x="0" y="0" width="24" height="24"><rect width="24" height="24" fill="#fff"/><g fill="#000"><path d="M10.6 20v-2.4a1.4 1.4 0 0 1 2.8 0V20z"/></g></mask></defs><g mask="url(#__ID__0)"><rect x="1.5" y="20" width="21" height="2" rx=".6"/><path d="M2.4 20L2.4 12L2 12L4.4 7L6.8 12L6.4 12L6.4 20z"/><path d="M17.6 20L17.6 12L17.2 12L19.6 7L22 12L21.6 12L21.6 20z"/><rect x="6.4" y="14.4" width="11.2" height="5.6"/><path d="M7.6 11.4L7.6 4.4L9.8 7.55L12 4.4L14.2 7.55L16.4 4.4L16.4 11.4z"/><circle cx="7.6" cy="4.4" r="1.2"/><circle cx="12" cy="4.4" r="1.2"/><circle cx="16.4" cy="4.4" r="1.2"/></g>' };
const i_tier_platinum: IconDef = { viewBox: '0 0 24 24', body: '<defs><mask id="__ID__0" maskUnits="userSpaceOnUse" x="0" y="0" width="24" height="24"><rect width="24" height="24" fill="#fff"/><g fill="#000"><path d="M10.4 20v-3a1.6 1.6 0 0 1 3.2 0v3z"/></g></mask></defs><g mask="url(#__ID__0)"><rect x="1.5" y="20" width="21" height="2" rx=".6"/><path d="M2.4 20L2.4 9.4L2 9.4L4.6 3L7.2 9.4L6.8 9.4L6.8 20z"/><path d="M17.2 20L17.2 9.4L16.8 9.4L19.4 3L22 9.4L21.6 9.4L21.6 20z"/><rect x="6.8" y="12.4" width="10.4" height="7.6"/><rect x="8" y="10.4" width="1.6" height="2.4"/><rect x="10.8" y="10.4" width="1.6" height="2.4"/><rect x="13.6" y="10.4" width="1.6" height="2.4"/></g>' };
const i_tier_silver: IconDef = { viewBox: '0 0 24 24', body: '<g><rect x="2" y="20" width="20" height="2" rx=".6"/><path d="M2.6 20L2.6 15.4L2.1 15.4L5.3 11.4L8.5 15.4L8 15.4L8 20z"/><path d="M9.3 20L9.3 14L8.8 14L12 9.2L15.2 14L14.7 14L14.7 20z"/><path d="M16 20L16 15.4L15.5 15.4L18.7 11.4L21.9 15.4L21.4 15.4L21.4 20z"/></g>' };
const i_tier_unranked: IconDef = { viewBox: '0 0 24 24', body: '<g><rect x="2" y="20" width="3.4" height="2" rx=".6"/><rect x="6.9" y="20" width="3.4" height="2" rx=".6"/><rect x="11.8" y="20" width="3.4" height="2" rx=".6"/><rect x="16.7" y="20" width="3.4" height="2" rx=".6"/><path d="M8.6 7.6a3.4 3.4 0 1 1 5 3c-1 .6-1.6 1.4-1.6 2.6v1" fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round"/><circle cx="12" cy="17.2" r="1.4"/></g>' };
const i_timer: IconDef = { viewBox: '0 0 24 24', body: '<defs><mask id="__ID__0" maskUnits="userSpaceOnUse" x="0" y="0" width="24" height="24"><rect width="24" height="24" fill="#fff"/><g fill="#000"><path d="M8.5 5.8h7c-.4 2.6-2.6 3.9-3.5 5.2-.9-1.3-3.1-2.6-3.5-5.2z"/><path d="M12 12.9v3" stroke="#000" stroke-width=".9"/></g></mask></defs><g mask="url(#__ID__0)"><rect x="4.5" y="2" width="15" height="2.4" rx=".6"/><rect x="4.5" y="19.6" width="15" height="2.4" rx=".6"/><path d="M6.4 4.2h11.2c0 4.3-3.5 6.3-4.3 7.8.8 1.5 4.3 3.5 4.3 7.8H6.4c0-4.3 3.5-6.3 4.3-7.8-.8-1.5-4.3-3.5-4.3-7.8z"/></g>' };
const i_to_start: IconDef = { viewBox: '0 0 24 24', body: '<g><rect x="2.6" y="5" width="2.4" height="14" rx=".6"/><path d="M14 5.6 7 12l7 6.4z" stroke="currentColor" stroke-width="1.2" stroke-linejoin="round"/><path d="M21.2 5.6 14.2 12l7 6.4z" stroke="currentColor" stroke-width="1.2" stroke-linejoin="round"/></g>' };
const i_tool_fill: IconDef = { viewBox: '0 0 24 24', body: '<g><g transform="rotate(40 10.2 13)"><path d="M4.6 8.8h11.2l-1.4 10.4a1.6 1.6 0 0 1-1.6 1.4H7.6A1.6 1.6 0 0 1 6 19.2z"/><rect x="3.6" y="6.4" width="13.2" height="2.6" rx=".8"/><path d="M6 6.6a4.2 4.2 0 0 1 8.4 0" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="butt" stroke-linejoin="round"/></g></g><g><path d="M19.4 12.4q2.8 3.6 2.8 5.4a2.8 2.8 0 0 1-5.6 0q0-1.8 2.8-5.4z"/></g>' };
const i_tool_line: IconDef = { viewBox: '0 0 24 24', body: '<g><path d="M6 18 18 6" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="butt" stroke-linejoin="round"/><rect x="2.6" y="16.4" width="5" height="5" rx=".8"/><rect x="16.4" y="2.6" width="5" height="5" rx=".8"/></g>' };
const i_tool_pan: IconDef = { viewBox: '0 0 24 24', body: '<g><rect x="6.2" y="4.4" width="2.4" height="10" rx="1.2"/><rect x="9.8" y="2.6" width="2.4" height="11" rx="1.2"/><rect x="13.4" y="3.4" width="2.4" height="10.5" rx="1.2"/><rect x="17" y="5.8" width="2.4" height="8.5" rx="1.2"/><path d="M6.2 11.6h13.2v4.6c0 3.2-2.4 5.6-5.6 5.6h-2.6c-2 0-3.4-.8-4.6-2.4L2.8 14.2a1.6 1.6 0 0 1 2.4-2.1l1 1.2z"/></g>' };
const i_tool_pick: IconDef = { viewBox: '0 0 24 24', body: '<g><g transform="rotate(45 12 12)"><rect x="9.2" y="1.6" width="5.6" height="6.8" rx="2.8"/><rect x="7.6" y="7.8" width="8.8" height="2.6" rx=".6"/><path d="M9.8 11.8h4.4v6.6L12 22.4l-2.2-4z"/></g></g>' };
const i_tool_select: IconDef = { viewBox: '0 0 24 24', body: '<g><path d="M5.4 2.8v16.6l4.2-4 3 6.4 3-1.4-3-6.3h6z" stroke="currentColor" stroke-width="1.2" stroke-linejoin="round"/></g>' };
const i_tower: IconDef = { viewBox: '0 0 24 24', body: '<defs><mask id="__ID__0" maskUnits="userSpaceOnUse" x="0" y="0" width="24" height="24"><rect width="24" height="24" fill="#fff"/><g fill="#000"><rect x="11.3" y="10.6" width="1.4" height="3.6"/><path d="M10.6 20v-1.8a1.4 1.4 0 0 1 2.8 0V20z"/></g></mask></defs><g mask="url(#__ID__0)"><rect x="1.5" y="20" width="21" height="2" rx=".6"/><path d="M8.6 21 9.2 8.6h5.6l.6 12.4z"/><rect x="6.4" y="6" width="11.2" height="3" rx=".5"/><rect x="6.4" y="3" width="2.2" height="3.6"/><rect x="10.9" y="3" width="2.2" height="3.6"/><rect x="15.4" y="3" width="2.2" height="3.6"/></g>' };
const i_trash: IconDef = { viewBox: '0 0 24 24', body: '<defs><mask id="__ID__0" maskUnits="userSpaceOnUse" x="0" y="0" width="24" height="24"><rect width="24" height="24" fill="#fff"/><g fill="#000"><rect x="8.6" y="10.4" width="1.6" height="8.6" rx=".5"/><rect x="13.8" y="10.4" width="1.6" height="8.6" rx=".5"/></g></mask></defs><g mask="url(#__ID__0)"><rect x="3.6" y="4.6" width="16.8" height="2.4" rx=".6"/><path d="M9.4 4.6V2.8h5.2v1.8z"/><path d="M5.4 8.2h13.2l-1.2 13.2H6.6z"/></g>' };
const i_undo: IconDef = { viewBox: '0 0 24 24', body: '<g><path d="M8 8.6h6.4a5.4 5.4 0 0 1 0 10.8H7.6" fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="butt" stroke-linejoin="round"/><path d="M2.6 8.6 8.6 3.4v10.4z"/></g>' };
const i_unit_catapult: IconDef = { viewBox: '0 0 24 24', body: '<defs><mask id="__ID__0" maskUnits="userSpaceOnUse" x="0" y="0" width="24" height="24"><rect width="24" height="24" fill="#fff"/><g fill="#000"><circle cx="6.4" cy="18.6" r="3.6" fill="none" stroke="#000" stroke-width="1.3"/><circle cx="17.6" cy="18.6" r="3.6" fill="none" stroke="#000" stroke-width="1.3"/></g></mask><mask id="__ID__1" maskUnits="userSpaceOnUse" x="0" y="0" width="24" height="24"><rect width="24" height="24" fill="#fff"/><g fill="#000"><circle cx="6.4" cy="18.6" r=".9"/><circle cx="17.6" cy="18.6" r=".9"/></g></mask></defs><g mask="url(#__ID__0)"><rect x="2.4" y="13.6" width="19.2" height="2.6" rx=".6"/><rect x="13.2" y="8" width="2.4" height="6"/><path d="M17.6 13.4 6.4 5.6" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="butt" stroke-linejoin="round"/><path d="M2.2 6.6a3.4 3.4 0 0 0 6.6-1.6z"/></g><g mask="url(#__ID__1)"><circle cx="6.4" cy="18.6" r="2.9"/><circle cx="17.6" cy="18.6" r="2.9"/></g>' };
const i_unit_cavalry: IconDef = { viewBox: '0 0 24 24', body: '<defs><mask id="__ID__0" maskUnits="userSpaceOnUse" x="0" y="0" width="24" height="24"><rect width="24" height="24" fill="#fff"/><g fill="#000"><circle cx="9.4" cy="8.8" r="1.1"/><path d="M14.6 6.4C17 7.8 18.6 10.6 18.8 14.4" fill="none" stroke="#000" stroke-width="1.3" stroke-linecap="butt" stroke-linejoin="round"/></g></mask></defs><g mask="url(#__ID__0)"><path d="M7 21.6C7.6 19 9 16.8 9.6 15.6L5 15.8C3.8 15.8 3 14.8 3.2 13.6l.4-1.4 7-7.2.8-2.6 2.2 2C17.6 5.4 20.4 9.4 20.4 14.6v7z"/></g>' };
const i_unit_golem: IconDef = { viewBox: '0 0 24 24', body: '<defs><mask id="__ID__0" maskUnits="userSpaceOnUse" x="0" y="0" width="24" height="24"><rect width="24" height="24" fill="#fff"/><g fill="#000"><rect x="10.8" y="4.8" width="2.4" height="1.3"/><path d="M1.6 11.8 7.6 12.8M22.4 11.8l-6 1" fill="none" stroke="#000" stroke-width="1.2" stroke-linecap="butt" stroke-linejoin="round"/></g></mask></defs><g mask="url(#__ID__0)"><path d="M10.3 3L13.7 3L14.4 7.6L9.6 7.6z"/><path d="M2.2 8.6L3.6 4.8L7.6 4.2L8.4 8.2L7.2 12L6.6 15.4L7.2 19.4L2.2 19.4L2.6 15z"/><path d="M21.8 8.6L20.4 4.8L16.4 4.2L15.6 8.2L16.8 12L17.4 15.4L16.8 19.4L21.8 19.4L21.4 15z"/><path d="M9.9 9L14.1 9L15.6 12L14.8 16L9.2 16L8.4 12z"/><path d="M8.8 17.4L11.3 17.4L11.3 21.6L8.4 21.6z"/><path d="M12.7 17.4L15.2 17.4L15.6 21.6L12.7 21.6z"/></g>' };
const i_unit_ram: IconDef = { viewBox: '0 0 24 24', body: '<g><path d="M2.4 11.4 9.6 4.4l7.2 7z"/><rect x="3" y="12.8" width="16" height="3"/><rect x="18.4" y="11.4" width="3.6" height="5.8" rx="1"/><circle cx="6.6" cy="19.6" r="2.4"/><circle cx="14.4" cy="19.6" r="2.4"/></g>' };
const i_unit_worker: IconDef = { viewBox: '0 0 24 24', body: '<defs><mask id="__ID__0" maskUnits="userSpaceOnUse" x="0" y="0" width="24" height="24"><rect width="24" height="24" fill="#fff"/><g fill="#000"><path d="M4.4 9.8h15.2" stroke="#000" stroke-width="1.1"/></g></mask></defs><g mask="url(#__ID__0)"><circle cx="12" cy="11.6" r="3.4"/><path d="M4.2 21.8v-2.4a7.8 6 0 0 1 15.6 0v2.4z"/><ellipse cx="12" cy="8.1" rx="7.4" ry="1.6"/><path d="M8.7 8.3 9.4 4.1q2.6-1.2 5.2 0l.7 4.2z"/></g>' };
const i_upg_range: IconDef = { viewBox: '0 0 24 24', body: '<g><rect x="2.6" y="5.8" width="13.4" height="2.2" rx=".5"/><path d="M15 2.8 21.4 6.9 15 11z"/><rect x="2.4" y="13" width="2.2" height="8.6" rx=".5"/><rect x="19.4" y="13" width="2.2" height="8.6" rx=".5"/><rect x="8.4" y="16.5" width="7.2" height="2"/><path d="M5.6 17.5 9.4 14.4v6.2zM18.4 17.5l-3.8-3.1v6.2z"/></g>' };
const i_vs_ai: IconDef = { viewBox: '0 0 24 24', body: '<defs><mask id="__ID__0" maskUnits="userSpaceOnUse" x="0" y="0" width="24" height="24"><rect width="24" height="24" fill="#fff"/><g fill="#000"><g transform="rotate(-45 12 12)"><path d="M10.8 15.2V4.4L12 2l1.2 2.4v10.8z M7.6 15h8.8v2H7.6z M11.05 16.6h1.9v3.6h-1.9z" fill="none" stroke="#000" stroke-width="1.5"/><circle cx="12" cy="21.3" r="1.45" fill="none" stroke="#000" stroke-width="1.5"/></g></g></mask></defs><g mask="url(#__ID__0)"><g transform="rotate(45 12 12)"><path d="M10.8 15.2V4.4L12 2l1.2 2.4v10.8z"/><rect x="7.6" y="15" width="8.8" height="2" rx=".6"/><rect x="11.05" y="16.6" width="1.9" height="3.6"/><circle cx="12" cy="21.3" r="1.45"/></g></g><g><g transform="rotate(-45 12 12)"><path d="M10.8 15.2V4.4L12 2l1.2 2.4v10.8z"/><rect x="7.6" y="15" width="8.8" height="2" rx=".6"/><rect x="11.05" y="16.6" width="1.9" height="3.6"/><circle cx="12" cy="21.3" r="1.45"/></g></g>' };
const i_warning: IconDef = { viewBox: '0 0 24 24', body: '<defs><mask id="__ID__0" maskUnits="userSpaceOnUse" x="0" y="0" width="24" height="24"><rect width="24" height="24" fill="#fff"/><g fill="#000"><path d="M10.85 8.4h2.3l-.4 6.8h-1.5z"/><circle cx="12" cy="17.4" r="1.3"/></g></mask></defs><g mask="url(#__ID__0)"><path d="M12 3.4 21.2 19.8H2.8z" stroke="currentColor" stroke-width="1.8" stroke-linejoin="round"/></g>' };

export const ICONS = {
  'abl-incendiary': i_abl_incendiary,
  'abl-shield': i_abl_shield,
  'abl-volley': i_abl_volley,
  'account': i_account,
  'age-1': i_age_1,
  'age-2': i_age_2,
  'age-up': i_age_up,
  'armor': i_armor,
  'attack-move': i_attack_move,
  'back': i_back,
  'barracks': i_barracks,
  'build': i_build,
  'cancel': i_cancel,
  'castle': i_castle,
  'chart': i_chart,
  'chat': i_chat,
  'check': i_check,
  'chevron': i_chevron,
  'clear': i_clear,
  'close': i_close,
  'copy': i_copy,
  'cross': i_cross,
  'dice': i_dice,
  'dismantle': i_dismantle,
  'eject': i_eject,
  'emblem': i_emblem,
  'error': i_error,
  'eye': i_eye,
  'fast-forward': i_fast_forward,
  'fence': i_fence,
  'flag': i_flag,
  'forge': i_forge,
  'fullscreen': i_fullscreen,
  'gate': i_gate,
  'gold-vein': i_gold_vein,
  'gold': i_gold,
  'hold': i_hold,
  'house': i_house,
  'idle-worker': i_idle_worker,
  'import': i_import,
  'info': i_info,
  'like': i_like,
  'link': i_link,
  'lock': i_lock,
  'map-editor': i_map_editor,
  'menu': i_menu,
  'militia': i_militia,
  'mine': i_mine,
  'minus': i_minus,
  'multiplayer': i_multiplayer,
  'new': i_new,
  'patrol': i_patrol,
  'pause': i_pause,
  'pencil': i_pencil,
  'pin': i_pin,
  'play-game': i_play_game,
  'play': i_play,
  'plus': i_plus,
  'population': i_population,
  'rally': i_rally,
  'range': i_range,
  'ranked': i_ranked,
  'redo': i_redo,
  'replay': i_replay,
  'resize': i_resize,
  'rotate-device': i_rotate_device,
  'save': i_save,
  'settings': i_settings,
  'shape-round': i_shape_round,
  'speed': i_speed,
  'stop': i_stop,
  'sword': i_sword,
  'sym-none': i_sym_none,
  'sym-rot': i_sym_rot,
  'sym-rot4': i_sym_rot4,
  'sym-x': i_sym_x,
  'sym-xy': i_sym_xy,
  'sym-y': i_sym_y,
  'take-slot': i_take_slot,
  'tier-bronze': i_tier_bronze,
  'tier-diamond': i_tier_diamond,
  'tier-gold': i_tier_gold,
  'tier-grandmaster': i_tier_grandmaster,
  'tier-master': i_tier_master,
  'tier-platinum': i_tier_platinum,
  'tier-silver': i_tier_silver,
  'tier-unranked': i_tier_unranked,
  'timer': i_timer,
  'to-start': i_to_start,
  'tool-fill': i_tool_fill,
  'tool-line': i_tool_line,
  'tool-pan': i_tool_pan,
  'tool-pick': i_tool_pick,
  'tool-select': i_tool_select,
  'tower': i_tower,
  'trash': i_trash,
  'undo': i_undo,
  'unit-catapult': i_unit_catapult,
  'unit-cavalry': i_unit_cavalry,
  'unit-golem': i_unit_golem,
  'unit-ram': i_unit_ram,
  'unit-worker': i_unit_worker,
  'upg-range': i_upg_range,
  'vs-ai': i_vs_ai,
  'warning': i_warning,
  // aliases: a game meaning drawn with another icon until it has its own
  'roster': i_population,
  'summary': i_chart,
  'battle': i_vs_ai,
  'skirmish': i_vs_ai,
  'replays': i_replay,
  'replay-again': i_replay,
  'about': i_info,
  'public': i_multiplayer,
  'community': i_multiplayer,
  'delete': i_trash,
  'edit': i_pencil,
  'download': i_save,
  'export': i_save,
  'more': i_chevron,
  'panel': i_menu,
  'scatter': i_dice,
  'zoom-in': i_plus,
  'zoom-out': i_minus,
  'fit': i_fullscreen,
  'age-marker': i_age_2,
  'tool-brush': i_pencil,
  'tool-rect': i_stop,
  'tool-mine': i_gold,
  'tool-spawn': i_castle,
  'tool-golem': i_unit_golem,
  'shape-square': i_stop,
  'anchor': i_stop,
  'unit-soldier': i_sword,
  'unit-archer': i_range,
  'unit-militia': i_militia,
  'upg-melee': i_sword,
  'upg-ranged': i_range,
  'upg-armor': i_armor,
  'upg-speed': i_speed,
  'upg-gather': i_gold,
  'abl-militia': i_militia,
} as const;

/** alias -> the icon it borrows (mirrored ones are marked) */
export const ICON_ALIASES: Readonly<Record<string, string>> = {
  'roster': 'population',
  'summary': 'chart',
  'battle': 'vs-ai',
  'skirmish': 'vs-ai',
  'replays': 'replay',
  'replay-again': 'replay',
  'about': 'info',
  'public': 'multiplayer',
  'community': 'multiplayer',
  'delete': 'trash',
  'edit': 'pencil',
  'download': 'save',
  'export': 'save',
  'more': 'chevron',
  'panel': 'menu',
  'scatter': 'dice',
  'zoom-in': 'plus',
  'zoom-out': 'minus',
  'fit': 'fullscreen',
  'age-marker': 'age-2',
  'tool-brush': 'pencil',
  'tool-rect': 'stop',
  'tool-mine': 'gold',
  'tool-spawn': 'castle',
  'tool-golem': 'unit-golem',
  'shape-square': 'stop',
  'anchor': 'stop',
  'unit-soldier': 'sword',
  'unit-archer': 'range',
  'unit-militia': 'militia',
  'upg-melee': 'sword',
  'upg-ranged': 'range',
  'upg-armor': 'armor',
  'upg-speed': 'speed',
  'upg-gather': 'gold',
  'abl-militia': 'militia',
};
